In [68]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.datasets import fetch_california_housing

In [69]:
housing = fetch_california_housing(as_frame=True)

df = housing.frame

df.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422

In [70]:
df.shape

(20640, 9)

In [71]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   MedInc       20640 non-null  float64
 1   HouseAge     20640 non-null  float64
 2   AveRooms     20640 non-null  float64
 3   AveBedrms    20640 non-null  float64
 4   Population   20640 non-null  float64
 5   AveOccup     20640 non-null  float64
 6   Latitude     20640 non-null  float64
 7   Longitude    20640 non-null  float64
 8   MedHouseVal  20640 non-null  float64
dtypes: float64(9)
memory usage: 1.4 MB

In [72]:
from sklearn.datasets import fetch_california_housing

boston_df = fetch_california_housing(as_frame=True)

x = pd.DataFrame(boston_df.data, columns=boston_df.feature_names)
y = boston_df.target

x.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25

In [73]:
##Independent features
x = pd.DataFrame(boston_df.data,columns = boston_df.feature_names)
y = boston_df.target
x.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25

In [74]:
# Train Test Split

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    x,
    y,
    test_size=0.33,
    random_state=42
)

print("X_train shape:", x_train.shape)
print("X_test shape:", x_test.shape)
print("Y_train shape:", y_train.shape)
print("Y_test shape:", y_test.shape)

X_train shape: (13828, 8)
X_test shape: (6812, 8)
Y_train shape: (13828,)
Y_test shape: (6812,)

In [75]:
from sklearn.tree import DecisionTreeRegressor

In [76]:
regressor = DecisionTreeRegressor()

In [77]:
regressor.fit(x_train,y_train)

DecisionTreeRegressor()

In [78]:
y_pred = regressor.predict(x_test)

In [79]:
y_pred

array([0.565  , 0.521  , 5.00001, ..., 1.264  , 1.387  , 5.00001],
      shape=(6812,))

In [80]:
from sklearn.metrics import r2_score

In [81]:
score = r2_score(y_pred,y_test)

score

In [82]:
##Hyperparameter tunning
parameter = {
    'criterion':['squared_error','friedman_mse','absolute_error','poission'],
    'splitter': ['best','random'],
    'max_depth':[1,2,3,4,5,6,7,8,10,11,12],
    'max_features':['auto','sqrt','log2'],
}

In [83]:
regressor = DecisionTreeRegressor()

In [84]:
from sklearn.model_selection import GridSearchCV

In [85]:
regressor = GridSearchCV(regressor,param_grid = parameter,cv=5,scoring = 'neg_mean_squared')

In [88]:
from sklearn.model_selection import GridSearchCV

regressorcv = GridSearchCV(
    estimator=regressor,
    param_grid=parameter,
    cv=5,
    scoring='neg_mean_squared_error'
)

In [90]:
# 1
from sklearn.model_selection import GridSearchCV

# 2
regressorcv = GridSearchCV(
    estimator=regressor,
    param_grid=parameter,
    cv=5,
    scoring='neg_mean_squared_error'
)

# 3
regressorcv.fit(x_train, y_train)

# 4
print("Best Parameters:", regressorcv.best_params_)

# 5
y_pred = regressorcv.predict(x_test)

# 6
from sklearn.metrics import r2_score
print("R2 Score:", r2_score(y_test, y_pred))

ValueError: Invalid parameter 'criterion' for estimator GridSearchCV(cv=5, estimator=DecisionTreeRegressor(),
             param_grid={'criterion': ['squared_error', 'friedman_mse',
                                       'absolute_error', 'poission'],
                         'max_depth': [1, 2, 3, 4, 5, 6, 7, 8, 10, 11, 12],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             scoring='neg_mean_squared'). Valid parameters are: ['cv', 'error_score', 'estimator', 'n_jobs', 'param_grid', 'pre_dispatch', 'refit', 'return_train_score', 'scoring', 'verbose'].

In [ ]:
y_pred = regressorcv.predict(x_test)

In [ ]:
r2_score(y_pred,y_test)

In [87]:
score

0.5962651325850131